version: "3.7"

networks: 
  default: 
    external:
      name: flexric_connection

services:
  flexric:
    image: flexric_experiments
    container_name: Flexric
    command: sh -c "echo -e "[NEAR-RIC]\nNEAR_RIC_IP = 172.18.0.2\n\n[XAPP]\nDB_DIR=/tmp/" > flexric/flexric.conf && flexric/build/examples/ric/nearRT-RIC -c flexric/flexric.conf"
  
  cu:
    image: flexric_experiments
    container_name: Cu
    command: sh -c "echo -e "[NEAR-RIC]\nNEAR_RIC_IP = 172.18.0.2\n\n[XAPP]\nDB_DIR = /tmp/" > flexric/flexric.conf && flexric/build/examples/emulator/agent/emu_agent_gnb_cu -c flexric/flexric.conf"
    depends_on:
      - flexric
  
  du:
    image: flexric_experiments
    container_name: Du
    command: sh -c "echo -e "[NEAR-RIC]\nNEAR_RIC_IP = 172.18.0.2\n\n[XAPP]\nDB_DIR = /tmp/" > flexric/flexric.conf && flexric/build/examples/emulator/agent/emu_agent_gnb_du -c flexric/flexric.conf"
    depends_on:
        - flexric
